### ISSUE TITLE
Not getting plot for phylogeny of rice cultivars

### ISSUE THREAD

**Issue by Ravindra-Raut** [galacticpolymath/galacticEdTools#3]
I was trying to get a plot for rice cultivars. But getting the following error:

Error in showPhylo(speciesNames, nameType = "scientific") : 
 *Some species records not matched. Try changing your search terms.
In addition: Warning message:
Oryza sativa A123, Oryza sativa HEG4, Oryza sativa Suijing18,  Oryza sativa Hitomebore, Oryza sativa Nipponbare, Oryza sativa Shennong 265 are not matched

Is it possible to generate a dated phylogenic tree for Oryza cultivars with this tool.

**Comment by drwilkins** [comment]
Hi Ravindra,

The tree architecture is based on Open Tree of Life
***@***.***>, so
if your search taxa aren't in there, it will get stuck at that stage
(before generating a cladogram). The dated tree is an even more restrictive
stage that depends on availability of divergence estimates in the
literature (see datelife <http://phylotastic.org/datelife/>).

------------
Matt Wilkins, PhD (he/him)
Founder, CEO
Galactic Polymath <http://galacticpolymath.com/>
@mattwilkinsbio <https://twitter.com/mattwilkinsbio>
@galacticPM <http://twitter.com/galacticPM>

**Comment by Ravindra-Raut** [comment]
Thanks for sharing the information. Could you please suggest any tool that will help to sort this problem?

**Comment by drwilkins** [comment]
Sorry, I don't know. I created this as a quick-and-easy tool for educators
to show well-researched species-level differences between species. It's not
intended to work for subspecies/cultivar level trees. If you have sequence
data or know the tree topology, you can use ggtree to visualize your tree
<https://yulab-smu.top/treedata-book/>. That's one of the main packages
showPhylo uses.

------------
Matt Wilkins, PhD (he/him)
Founder, CEO
Galactic Polymath <http://galacticpolymath.com/>
@mattwilkinsbio <https://twitter.com/mattwilkinsbio>
@galacticPM <http://twitter.com/galacticPM>

**Comment by Ravindra-Raut** [comment]
Thanks, I appreciate your time and help.
