### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by LunaSare** [galacticpolymath/galacticEdTools#4]
Hi Matt!

Do you have a citation for the package yet? If not, you can tag a released version of your package on GitHub and generate a citable doi for it, it might be worthy. I would cite you!

**Comment by drwilkins** [comment]
Hey Luna,

I finally got around to checking out Zenodo. If you ever want to cite it, I
now have a DOI: Wilkins, M. R. (2021). galacticpolymath/galacticEdTools: R
Tools for K-16 Teaching (Version 0.1.3) [Computer software].
https://doi.org/10.5281/zenodo.6563892

Thanks for the tip!

Cheers,
Matt

------------
Matt Wilkins, PhD (he/him)
Founder, CEO
Galactic Polymath <http://galacticpolymath.com/>
@mattwilkinsbio <https://twitter.com/mattwilkinsbio>
@galacticPM <http://twitter.com/galacticPM>
